### ISSUE TITLE
Hi-Fi Rush (Steam) crashes on boot

### ISSUE THREAD

**Issue by MinionJax** [AnimatedSwine37/UnrealEssentials#14]
Whenever I try to launch Hi-Fi Rush with mods I've downloaded from nexusmods.com, I get this result:
[Error Log.txt](https://github.com/user-attachments/files/17794081/Error.Log.txt)

Folder structure example:
![Screenshot 2024-11-17 210446](https://github.com/user-attachments/assets/6cddb5bc-84c5-4d8c-a391-62dab641db9d)

I believe I have everything set up correctly, as well as the latest version of UnrealEssentials, so I'm a little lost on how to fix this issue...
Any help would be appreciated :)

**Comment by AnimatedSwine37** [comment]
This seems to be a bug where the game will crash if you only include full utoc files like this instead of having unpacked files using utoc emulator. What you are doing should be right.

I've updated UTOC/IO Store Emulator to 1.1.2 which seems to have fixed the problem for me. Let me know if that works for you, you should be prompted to update it when you open up Reloaded.

**Comment by MinionJax** [comment]
(Sorry for responding late)
OMG it works now!! Thank you so much for taking the time to look into the issue ^v^
